### ISSUE TITLE
Querying headers on content that requires authorisation

### ISSUE THREAD

**Issue by jamieRowen-mediacom** [jumpingrivers/serverheaders#11]
Is there any way that this might be added? In many cases it could potentially be resolved by allowing arguments to be passed through to the `{httr}` methods thereby allowing me to provide headers with the request?

**Comment by csgillespie** [comment]
I'm being naive here, but can you give me an example of what you are after?

What sort of auth do you mean?

**Comment by jamieRowen-mediacom** [comment]
As an example what if I wanted to inspect the headers of say a private GitHub repos gh-pages site? Ignoring for a second that it probably doesn't matter on my static site what they are. Or any non-public shiny app I might have for example

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by csgillespie** [comment]
OK. In my head, for many situations (but not all), the auth page is the same server as page your care about.  For example, Connect requires auth to access it, but the server headers should still be the same. 

In other situations, I'm not show. I suppose if you can give me an example of what should be passed through to {httr}, then I'm happy think about it / add it.

**Comment by csgillespie** [comment]
Need an example to work with. Happy to reopen
